feat: [Candidato] - Feed de vagas
SouJunior/vagas-backend pull request #103
Opened 2023-04-09 19:53 UTC by Amaro13

2023-04-10 12:34 UTC, wandersonDeve requested changes

2023-04-10 12:34 UTC, wandersonDeve commented on src/modules/jobs/services/search-job.service.ts
> +    const pageMetaDto = new PageMetaDto({ itemCount, pageOptionsDto });
Colocar todo o querybuild e paginação dentro do repository

2023-04-10 12:34 UTC, wandersonDeve commented on src/modules/mails/mail.module.ts
> +          secure: true,
Para não mudar na AWS voltar para false

2023-04-10 14:21 UTC, ronaldmiranda commented on src/modules/mails/mail.module.ts
> +          secure: true,
@wandersonDeve  Eu acho que esse valor poderia ser setável também.

2023-04-10 14:21 UTC, wandersonDeve commented on src/modules/mails/mail.module.ts
> +          secure: true,
pensei a mesma coisa, deixar na env

2023-04-10 14:22 UTC, ronaldmiranda commented on src/modules/mails/mail.module.ts
> +          secure: true,
@wandersonDeve 
E isso me remete a uma outra possibilidade, testar as funcionalidades de email usando o https://github.com/mailhog/MailHog

2023-04-13 02:42 UTC, Amaro13 commented on src/modules/jobs/services/search-job.service.ts
> +    const pageMetaDto = new PageMetaDto({ itemCount, pageOptionsDto });
Fiz novo commit com essa correção. Commit: af12781

2023-04-13 02:45 UTC, Amaro13 commented on src/modules/mails/mail.module.ts
> +          secure: true,
corrigido para false

2023-04-13 02:47 UTC, Amaro13 reviewed
Fiz as correções em commits

2023-04-13 03:52 UTC, wandersonDeve approved these changes

2023-04-13 03:53 UTC, merged