feat: adicionado confirmação de usuário criado por email
SouJunior/vagas-backend pull request #73
Opened 2023-02-23 19:44 UTC by Amaro13

2023-02-28 15:37 UTC, thiagorcode requested changes

2023-02-28 15:37 UTC, thiagorcode commented on src/modules/company/repository/company-repository.ts
> +    return this.save({
Podemos usar apenas o this.update()

2023-02-28 15:37 UTC, thiagorcode commented on src/modules/company/repository/company-repository.ts
> +    return this.save({
Podemos usar apenas o this.update()

2023-03-01 11:57 UTC, audicarmo commented on src/modules/mails/mail.service.ts
> +  // async sendCompanyConfirmation(company: CompaniesEntity) {
@Amaro13 Notei que há muito código comentado. Código que não usaremos podem ser removidos, assim mantemos apenas o importante e necessário em nossa aplicação.

2023-03-05 00:27 UTC, Amaro13 commented on src/modules/mails/mail.service.ts
> +  // async sendCompanyConfirmation(company: CompaniesEntity) {
eles estavam comentados para facilitar ativação no futuro, estavam desativados porque quando eu tinha criado tinha dúvidas sobre a entity da empresa.

2023-03-05 00:39 UTC, Amaro13 commented
Recuperar senha para usuário e empresa

2023-03-06 06:56 UTC, wandersonDeve commented on src/database/migrations/1676872272236-email.ts
> +import { MigrationInterface, QueryRunner } from "typeorm"
MIgration Vazia

2023-03-10 23:15 UTC, Amaro13 commented on src/database/migrations/1676872272236-email.ts
> +import { MigrationInterface, QueryRunner } from "typeorm"
removi a pasta migration

2023-03-10 23:16 UTC, closed without merging