feat: implementação de descrições das rotas
SouJunior/vagas-backend pull request #88
Opened 2023-03-31 00:06 UTC by nandoProgrammer

> -[x] Implementação de exemplo de sucesso da rota

> -[x] Implementação de exemplo de erros da rota

2023-03-31 00:32 UTC, wandersonDeve requested changes

2023-03-31 00:32 UTC, wandersonDeve commented on src/modules/user/user.controller.ts
> +    status: HttpStatus.UNAUTHORIZED,
Tá usando Unauthorized porem ta tipado como NotFound

2023-03-31 00:33 UTC, wandersonDeve commented on src/modules/user/user.controller.ts
> +    status: HttpStatus.UNAUTHORIZED,
Verifica os outros campos se esta assim tbm

2023-04-01 00:34 UTC, nandoProgrammer commented on src/modules/user/user.controller.ts
> +    status: HttpStatus.UNAUTHORIZED,
segui o exemplo do auth

2023-04-01 02:12 UTC, wandersonDeve requested changes

2023-04-01 02:12 UTC, wandersonDeve commented on src/modules/company/company.controller.ts
> +    type: CreateCompanyDto,
Esses dado são o de envio, não o de retorno, verifica no swagger e valida fazendo uma requisição. O mesmo para as demais rotas

2023-04-04 17:27 UTC, merged